### ISSUE TITLE
Creating a new package inside an existing package fails

### ISSUE THREAD

**Issue by bates64** [nanaian/starpkg#2]
```sh
$ mkdir parent_package
$ cd parent_package
$ starpkg new parent_package

# Doesn't work, but should:
$ starpkg new child_package

# Also doesn't work, but should:
$ mkdir child_package
$ cd child_package
$ starpkg new child_package
```

In both cases, we get a `directory /path/to/parent_package is already a package` error :/

**Comment by CountHomer69** [comment]
Why are you posting issues of your own program? I don't think anyone else may be able to help since you're the dev.

**Comment by bates64** [comment]
@CountHomer69 It helps me keep track of issues I need to fix (i.e. known issues), and its always open if anyone wants to contribute.

**Comment by bates64** [comment]
Added a test for this in 30ba899.
