### ISSUE TITLE
macOS build/install script is untested

### ISSUE THREAD

**Issue by bates64** [nanaian/starpkg#3]
![](https://cdn.discordapp.com/attachments/448779340600311808/673935479229513770/unknown.png)

The starpkg-unix.zip build we make doesn't work on MacOS. Perhaps we should create a job that builds on MacOS in particular?

**Comment by bates64** [comment]
Should be resolved by e320e976e5b2b1f9c35e62f9851fdccdf723738a, just need confirmation from a macOS user.

**Comment by Blue-Dot** [comment]
wget is not supported on MacOS :/

**Comment by bates64** [comment]
@Blue-Dot should be fixed in [this install script revision](https://gist.github.com/nanaian/cf9ca4e645d8b7b1951c42d2b9c6f2f6/revisions#diff-2eff7ff2b5d6c72df58beddacd90e97f)

**Comment by bates64** [comment]
Closing due to 789ac8a14bb9bd4d308f0ea981c8fabf2f781e51
